name: Build and Test

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    test:
        runs-on: ubuntu-latest
        environment: prod
        strategy:
            matrix:
                node-version: [18]

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: List build artifacts
              run: ls dist

            - name: Run tests
              env:
                  USERNAME_DB: ${{ secrets.USERNAME_DB }}
                  PASSWORD_DB: ${{ secrets.PASSWORD_DB }}
                  JWT: ${{ secrets.JWT }}
                  COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
              run: npm test
